### ISSUE TITLE
Code Quality: Replace `Newtonsoft.Json` with `System.Text.Json`

### ISSUE THREAD

**Issue by Lamparter** [FirebrowserDevs/FireBrowserWinUi3#28]
The JSON (de)serialiser included in the System namespace is far faster and will allow for quicker JSON serialisation and deserialisation.

---

![Image](https://github.com/user-attachments/assets/a67dd984-6a21-4337-af37-0aed70067dd5)

**Comment by jarno9981** [comment]
will work on it

**Comment by jarno9981** [comment]
Runtime now runs from system.text.json instead of newstonesoft.json

**Comment by jarno9981** [comment]
latest patch removes newstonesoft.json needed
